{{- if (include "ai-models.isEnabled" .) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-models.controllerServiceAccountName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "controller")) | nindent 2 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-models.publicationWorkerServiceAccountName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "publication-worker")) | nindent 2 }}
{{- end }}
