{{- if and (include "ai-models.isEnabled" .) (include "ai-models.hasAPI" (list . "monitoring.coreos.com/v1/ServiceMonitor")) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ai-models.controllerName" . }}
  namespace: {{ include "ai-models.monitoringNamespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "controller")) | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: "ai-models"
      component: "controller"
  endpoints:
    - bearerTokenSecret:
        key: token
        name: prometheus-token
      port: https-metrics
      path: /metrics
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - {{ include "ai-models.namespace" . }}
{{- end }}
