{{- if (include "ai-models.isEnabled" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-models.controllerServiceName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "controller")) | nindent 2 }}
    {{- include "ai-models.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  selector:
    {{- include "ai-models.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
    - name: https-metrics
      port: {{ include "ai-models.controllerMetricsPort" . | int }}
      targetPort: https-metrics
      protocol: TCP
    - name: webhook
      port: {{ include "ai-models.controllerWebhookPort" . | int }}
      targetPort: webhook
      protocol: TCP
{{- end }}
