{{- if and (include "ai-models.isEnabled" .) (eq (include "ai-models.publicationStorageType" . | trim) "PersistentVolumeClaim") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-models.dmcrName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "dmcr")) | nindent 2 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ include "ai-models.publicationStoragePVCStorageSize" . | quote }}
  {{- if (include "ai-models.publicationStoragePVCStorageClassName" . | trim) }}
  storageClassName: {{ include "ai-models.publicationStoragePVCStorageClassName" . | quote }}
  {{- end }}
{{- end }}
