{{- if (include "ai-models.isEnabled" .) }}
{{- $namespace := include "ai-models.namespace" . -}}
{{- $cert := .Values.aiModels.internal.dmcr.cert -}}
{{- $auth := .Values.aiModels.internal.dmcr.auth -}}
{{- $writePassword := $auth.writePassword | trim -}}
{{- $readPassword := $auth.readPassword | trim -}}
{{- $writeHTPasswd := $auth.writeHtpasswd | trim -}}
{{- $readHTPasswd := $auth.readHtpasswd | trim -}}
{{- $writeHTPasswdChecksum := include "ai-models.dmcrPasswordChecksum" $writePassword | trim -}}
{{- $readHTPasswdChecksum := include "ai-models.dmcrPasswordChecksum" $readPassword | trim -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.dmcrTLSSecretName" . }}
  namespace: {{ $namespace }}
  annotations:
    {{ include "ai-models.dmcrSecretRestartChecksumAnnotationKey" . }}: {{ include "ai-models.dmcrTLSSecretRestartChecksum" . | quote }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "dmcr" "part" "tls")) | nindent 2 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $cert.ca | b64enc }}
  tls.crt: {{ $cert.crt | b64enc }}
  tls.key: {{ $cert.key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.dmcrCASecretName" . }}
  namespace: {{ $namespace }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "dmcr" "part" "ca")) | nindent 2 }}
type: Opaque
data:
  ca.crt: {{ $cert.ca | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.dmcrAuthSecretName" . }}
  namespace: {{ $namespace }}
  annotations:
    {{ include "ai-models.dmcrSecretRestartChecksumAnnotationKey" . }}: {{ include "ai-models.dmcrAuthSecretRestartChecksum" . | quote }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "dmcr" "part" "auth-server")) | nindent 2 }}
type: Opaque
stringData:
  write.password: {{ $writePassword | quote }}
  read.password: {{ $readPassword | quote }}
  write.htpasswd: |
{{ $writeHTPasswd | nindent 4 }}
  write.htpasswd.checksum: {{ $writeHTPasswdChecksum | quote }}
  read.htpasswd: |
{{ $readHTPasswd | nindent 4 }}
  read.htpasswd.checksum: {{ $readHTPasswdChecksum | quote }}
  htpasswd: |
{{ printf "%s\n%s" $writeHTPasswd $readHTPasswd | nindent 4 }}
  salt: {{ $auth.salt | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.dmcrWriteAuthSecretName" . }}
  namespace: {{ $namespace }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "dmcr" "part" "auth-write")) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
{{ include "ai-models.dmcrDockerConfigJSON" (list . (include "ai-models.dmcrWriteAuthUsername" . | trim) $writePassword) | nindent 4 }}
  username: {{ include "ai-models.dmcrWriteAuthUsername" . | quote }}
  password: {{ $writePassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.dmcrReadAuthSecretName" . }}
  namespace: {{ $namespace }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "dmcr" "part" "auth-read")) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
{{ include "ai-models.dmcrDockerConfigJSON" (list . (include "ai-models.dmcrReadAuthUsername" . | trim) $readPassword) | nindent 4 }}
  username: {{ include "ai-models.dmcrReadAuthUsername" . | quote }}
  password: {{ $readPassword | quote }}
{{- end }}
