//go:build !ignore_autogenerated

// Copyright 2026 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterModel) DeepCopyInto(out *ClusterModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterModel.
func (in *ClusterModel) DeepCopy() *ClusterModel {
	if in == nil {
		return nil
	}
	out := new(ClusterModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterModelList) DeepCopyInto(out *ClusterModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterModelList.
func (in *ClusterModelList) DeepCopy() *ClusterModelList {
	if in == nil {
		return nil
	}
	out := new(ClusterModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Model) DeepCopyInto(out *Model) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Model.
func (in *Model) DeepCopy() *Model {
	if in == nil {
		return nil
	}
	out := new(Model)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Model) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelArtifactStatus) DeepCopyInto(out *ModelArtifactStatus) {
	*out = *in
	if in.SizeBytes != nil {
		in, out := &in.SizeBytes, &out.SizeBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelArtifactStatus.
func (in *ModelArtifactStatus) DeepCopy() *ModelArtifactStatus {
	if in == nil {
		return nil
	}
	out := new(ModelArtifactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLaunchPolicy) DeepCopyInto(out *ModelLaunchPolicy) {
	*out = *in
	if in.AllowedRuntimes != nil {
		in, out := &in.AllowedRuntimes, &out.AllowedRuntimes
		*out = make([]ModelRuntimeEngine, len(*in))
		copy(*out, *in)
	}
	if in.AllowedAcceleratorVendors != nil {
		in, out := &in.AllowedAcceleratorVendors, &out.AllowedAcceleratorVendors
		*out = make([]ModelAcceleratorVendor, len(*in))
		copy(*out, *in)
	}
	if in.AllowedPrecisions != nil {
		in, out := &in.AllowedPrecisions, &out.AllowedPrecisions
		*out = make([]ModelPrecision, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLaunchPolicy.
func (in *ModelLaunchPolicy) DeepCopy() *ModelLaunchPolicy {
	if in == nil {
		return nil
	}
	out := new(ModelLaunchPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelList) DeepCopyInto(out *ModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Model, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelList.
func (in *ModelList) DeepCopy() *ModelList {
	if in == nil {
		return nil
	}
	out := new(ModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMinimumLaunchStatus) DeepCopyInto(out *ModelMinimumLaunchStatus) {
	*out = *in
	if in.AcceleratorCount != nil {
		in, out := &in.AcceleratorCount, &out.AcceleratorCount
		*out = new(int64)
		**out = **in
	}
	if in.AcceleratorMemoryGiB != nil {
		in, out := &in.AcceleratorMemoryGiB, &out.AcceleratorMemoryGiB
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMinimumLaunchStatus.
func (in *ModelMinimumLaunchStatus) DeepCopy() *ModelMinimumLaunchStatus {
	if in == nil {
		return nil
	}
	out := new(ModelMinimumLaunchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelOptimizationPolicy) DeepCopyInto(out *ModelOptimizationPolicy) {
	*out = *in
	if in.SpeculativeDecoding != nil {
		in, out := &in.SpeculativeDecoding, &out.SpeculativeDecoding
		*out = new(ModelSpeculativeDecodingPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelOptimizationPolicy.
func (in *ModelOptimizationPolicy) DeepCopy() *ModelOptimizationPolicy {
	if in == nil {
		return nil
	}
	out := new(ModelOptimizationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelReference) DeepCopyInto(out *ModelReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelReference.
func (in *ModelReference) DeepCopy() *ModelReference {
	if in == nil {
		return nil
	}
	out := new(ModelReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelResolvedStatus) DeepCopyInto(out *ModelResolvedStatus) {
	*out = *in
	if in.ParameterCount != nil {
		in, out := &in.ParameterCount, &out.ParameterCount
		*out = new(int64)
		**out = **in
	}
	if in.Quantization != nil {
		in, out := &in.Quantization, &out.Quantization
		*out = new(string)
		**out = **in
	}
	if in.ContextWindowTokens != nil {
		in, out := &in.ContextWindowTokens, &out.ContextWindowTokens
		*out = new(int64)
		**out = **in
	}
	if in.SupportedEndpointTypes != nil {
		in, out := &in.SupportedEndpointTypes, &out.SupportedEndpointTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompatibleRuntimes != nil {
		in, out := &in.CompatibleRuntimes, &out.CompatibleRuntimes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompatibleAcceleratorVendors != nil {
		in, out := &in.CompatibleAcceleratorVendors, &out.CompatibleAcceleratorVendors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompatiblePrecisions != nil {
		in, out := &in.CompatiblePrecisions, &out.CompatiblePrecisions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinimumLaunch != nil {
		in, out := &in.MinimumLaunch, &out.MinimumLaunch
		*out = new(ModelMinimumLaunchStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelResolvedStatus.
func (in *ModelResolvedStatus) DeepCopy() *ModelResolvedStatus {
	if in == nil {
		return nil
	}
	out := new(ModelResolvedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRuntimeHints) DeepCopyInto(out *ModelRuntimeHints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRuntimeHints.
func (in *ModelRuntimeHints) DeepCopy() *ModelRuntimeHints {
	if in == nil {
		return nil
	}
	out := new(ModelRuntimeHints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSourceSpec) DeepCopyInto(out *ModelSourceSpec) {
	*out = *in
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.Upload != nil {
		in, out := &in.Upload, &out.Upload
		*out = new(UploadModelSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSourceSpec.
func (in *ModelSourceSpec) DeepCopy() *ModelSourceSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.RuntimeHints != nil {
		in, out := &in.RuntimeHints, &out.RuntimeHints
		*out = new(ModelRuntimeHints)
		**out = **in
	}
	if in.UsagePolicy != nil {
		in, out := &in.UsagePolicy, &out.UsagePolicy
		*out = new(ModelUsagePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.LaunchPolicy != nil {
		in, out := &in.LaunchPolicy, &out.LaunchPolicy
		*out = new(ModelLaunchPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Optimization != nil {
		in, out := &in.Optimization, &out.Optimization
		*out = new(ModelOptimizationPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpeculativeDecodingPolicy) DeepCopyInto(out *ModelSpeculativeDecodingPolicy) {
	*out = *in
	if in.DraftModelRefs != nil {
		in, out := &in.DraftModelRefs, &out.DraftModelRefs
		*out = make([]ModelReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpeculativeDecodingPolicy.
func (in *ModelSpeculativeDecodingPolicy) DeepCopy() *ModelSpeculativeDecodingPolicy {
	if in == nil {
		return nil
	}
	out := new(ModelSpeculativeDecodingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(ResolvedSourceStatus)
		**out = **in
	}
	if in.Upload != nil {
		in, out := &in.Upload, &out.Upload
		*out = new(ModelUploadStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(ModelArtifactStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Resolved != nil {
		in, out := &in.Resolved, &out.Resolved
		*out = new(ModelResolvedStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelUploadStatus) DeepCopyInto(out *ModelUploadStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelUploadStatus.
func (in *ModelUploadStatus) DeepCopy() *ModelUploadStatus {
	if in == nil {
		return nil
	}
	out := new(ModelUploadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelUsagePolicy) DeepCopyInto(out *ModelUsagePolicy) {
	*out = *in
	if in.AllowedEndpointTypes != nil {
		in, out := &in.AllowedEndpointTypes, &out.AllowedEndpointTypes
		*out = make([]ModelEndpointType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelUsagePolicy.
func (in *ModelUsagePolicy) DeepCopy() *ModelUsagePolicy {
	if in == nil {
		return nil
	}
	out := new(ModelUsagePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedSourceStatus) DeepCopyInto(out *ResolvedSourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedSourceStatus.
func (in *ResolvedSourceStatus) DeepCopy() *ResolvedSourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadModelSource) DeepCopyInto(out *UploadModelSource) {
	*out = *in
	if in.ExpectedSizeBytes != nil {
		in, out := &in.ExpectedSizeBytes, &out.ExpectedSizeBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadModelSource.
func (in *UploadModelSource) DeepCopy() *UploadModelSource {
	if in == nil {
		return nil
	}
	out := new(UploadModelSource)
	in.DeepCopyInto(out)
	return out
}
