{{- if and (include "ai-models.isEnabled" .) (include "ai-models.hasAPI" (list . "monitoring.coreos.com/v1/ServiceMonitor")) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ai-models.fullname" . }}
  namespace: {{ include "ai-models.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "backend")) | nindent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "ai-models.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      basicAuth:
        username:
          name: {{ include "ai-models.backendAuthSecretName" . }}
          key: adminUsername
        password:
          name: {{ include "ai-models.backendAuthSecretName" . }}
          key: adminPassword
  namespaceSelector:
    matchNames:
      - {{ include "ai-models.namespace" . }}
{{- end }}
