{{- if (include "ai-models.isEnabled" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ai-models.uploadGatewayName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "upload-gateway")) | nindent 2 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ai-models.uploadGatewayName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "upload-gateway")) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ai-models.uploadGatewayName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ai-models.uploadGatewayServiceAccountName" . }}
    namespace: {{ include "ai-models.namespace" . }}
{{- end }}
