{{- $accessKey := include "ai-models.artifactsInlineAccessKey" . | trim -}}
{{- $secretKey := include "ai-models.artifactsInlineSecretKey" . | trim -}}
{{- $externalSecret := include "ai-models.artifactsCredentialsSecretName" . | trim -}}
{{- if and (include "ai-models.isEnabled" .) $accessKey $secretKey (not $externalSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.artifactsManagedSecretName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  labels:
    heritage: deckhouse
    module: {{ include "ai-models.moduleName" . }}
type: Opaque
stringData:
  accessKey: {{ $accessKey | quote }}
  secretKey: {{ $secretKey | quote }}
{{- end }}
