{{- if (include "ai-models.isEnabled" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.backendCryptoSecretName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  labels:
    heritage: deckhouse
    module: {{ include "ai-models.moduleName" . }}
type: Opaque
stringData:
  kekPassphrase: {{ include "ai-models.backendCryptoKEKPassphrase" . | quote }}
{{- end }}
