{{- if (include "ai-models.isEnabled" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.backendAuthSecretName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  labels:
    heritage: deckhouse
    module: {{ include "ai-models.moduleName" . }}
type: Opaque
stringData:
  machineUsername: {{ include "ai-models.backendAuthMachineUsername" . | quote }}
  machinePassword: {{ include "ai-models.backendAuthMachinePassword" . | quote }}
  flaskServerSecretKey: {{ include "ai-models.backendAuthFlaskSecretKey" . | quote }}
{{- end }}
