{{- if (include "ai-models.isEnabled" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.backendAuthSecretName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  labels:
    heritage: deckhouse
    module: {{ include "ai-models.moduleName" . }}
type: Opaque
stringData:
  adminUsername: {{ include "ai-models.backendAuthAdminUsername" . | quote }}
  adminPassword: {{ include "ai-models.backendAuthAdminPassword" . | quote }}
  flaskServerSecretKey: {{ include "ai-models.backendAuthFlaskSecretKey" . | quote }}
{{- end }}
