{{- $username := include "ai-models.publicationRegistryInlineUsername" . | trim -}}
{{- $password := include "ai-models.publicationRegistryInlinePassword" . | trim -}}
{{- $externalSecret := include "ai-models.publicationRegistryCredentialsSecretName" . | trim -}}
{{- if and (include "ai-models.isEnabled" .) $username $password (not $externalSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.publicationRegistryManagedSecretName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ai-models" "component" "module" "part" "publication-registry-secret")) | nindent 2 }}
type: Opaque
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
{{- end }}
