{{- $dockerConfig := include "ai-models.registryDockerConfig" . | trim -}}
{{- if $dockerConfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-models.registrySecretName" . }}
  namespace: {{ include "ai-models.namespace" . }}
  labels:
    heritage: deckhouse
    module: {{ include "ai-models.moduleName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerConfig | quote }}
{{- end }}
