{{- if (include "ai-models.isEnabled" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: ai-models
    rbac.deckhouse.io/aggregate-to-kubernetes-as: manager
    rbac.deckhouse.io/kind: use
  name: d8:use:capability:module:ai-models:edit
rules:
  - apiGroups: ["ai.deckhouse.io"]
    resources: ["models"]
    verbs: ["create", "update", "patch", "delete", "deletecollection"]
{{- end }}
