{{- if and (include "ai-models.dexEnabled" .) (include "ai-models.hasAPI" (list . "deckhouse.io/v1/DexAuthenticator")) }}
---
apiVersion: deckhouse.io/v1
kind: DexAuthenticator
metadata:
  name: ai-models
  namespace: {{ include "ai-models.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "dex-authenticator" "name" "ai-models")) | nindent 2 }}
spec:
  applicationDomain: {{ include "ai-models.publicHost" . }}
  {{- if (include "helm_lib_module_https_ingress_tls_enabled" .) }}
  applicationIngressCertificateSecretName: {{ include "helm_lib_module_https_secret_name" (list . "ingress-tls") }}
  {{- end }}
  applicationIngressClassName: {{ include "helm_lib_module_ingress_class" . | quote }}
  signOutURL: "/logout"
  sendAuthorizationHeader: true
  highAvailability: {{ not (empty (include "helm_lib_ha_enabled" .)) }}
{{- end }}
